export const FETCH_ACTORDETAILS = "FETCH_ACTORDETAILS";
export const FETCH_SEARCH = "FETCH_SEARCH";
export const FETCH_MOVIEDETAILS = "FETCH_MOVIEDETAILS";
export const FETCH_MOVIES = "FETCH_MOVIES";
